name: "Run prebuild's and Create GitHub and NPM release"
run-name: Package against ${{ github.ref_name }} # 每次运行的时候显示的名字

# 本yml参考于 https://github.com/WiseLibs/better-sqlite3/blob/master/.github/workflows/build.yml
on:
  workflow_dispatch: # 手动触发
    inputs: # 定义触发的时候可以输入的参数
      job: # 参数名称 通过 ${{ github.event.inputs.job }} 访问值 下面是参数的要求描述
        description: "任务类型"
        required: true
        default: prebuild
        type: string

env: # 用来定义环境变量 可用于工作流中所有作业的步骤的变量的 map
  # See https://github.com/nodejs/release#release-schedule
  # Node.js v16 EOL = 2023-09-11. v21 EOL = 2024-06-01.
  NODE_BUILD_CMD: npx --no-install prebuild -r node -t 16.0.0 -t  18.0.0 -t 20.0.0 -t 22.0.0  --include-regex 'sshcrypto.node$'
  # Merge with NODE_BUILD_CMD when Node.js v18 is EOL
  #  NO_V18_NODE_BUILD_CMD: npx --no-install prebuild -r node -t  20.0.0 -t 22.0.0 --include-regex 'node-word-detection.node$'
  # See https://www.electronjs.org/docs/latest/tutorial/electron-timelines#version-support-policy
  # Electron v25 EOL = 2023-12-05. v26 EOL = 2024-02-20. v27 EOL = 2024-04-16. v28 EOL = 2024-06-11. v29 EOL = 2024-08-20.
  ELECTRON_BUILD_CMD: npx --no-install prebuild -r electron -t 26.0.0 -t 27.0.0 -t 28.0.0 -t 29.0.0 -t 30.0.0 -t 31.0.0 -t 32.0.0  --include-regex 'sshcrypto.node$'

# 所有的jobs下的任务都会被执行
jobs:
  publish-npm:
    if: ${{ github.event.inputs.job == 'push-npm' || github.event.inputs.job == 'run-all' }}
    name: Publishing to NPM
    runs-on: ubuntu-20.04
      #needs: # 等待别的 job 任务完成
      #- prebuild
    #- prebuild-alpine
    #- prebuild-alpine-arm
    #- prebuild-linux-arm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  prebuild: # 执行node的 预构建
    if: ${{ github.event.inputs.job == 'prebuild'  || github.event.inputs.job == 'run-all'  }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-13
          - macos-14
          - windows-2022
    name: Prebuild on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    # needs: test
    steps:
      - uses: actions/checkout@v4 # 使用社区的指令
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: pip.exe install setuptools
      - if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install python-setuptools
      - if: ${{ !startsWith(matrix.os, 'windows') && !startsWith(matrix.os, 'macos') }}
        run: python3 -m pip install setuptools
      - if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt update
          sudo apt install -y libssl-dev
          sudo apt install gcc-10 g++-10 -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
      - run: npm install --ignore-scripts
      - run: ${{ env.NODE_BUILD_CMD }} -u ${{ secrets.GITHUB_TOKEN }}
      - run: ${{ env.ELECTRON_BUILD_CMD }} -u ${{ secrets.GITHUB_TOKEN }}
      - if: matrix.os == 'windows-2019'
        run: |
          ${{ env.NODE_BUILD_CMD }} -u ${{ secrets.GITHUB_TOKEN }}
          ${{ env.NODE_BUILD_CMD }} --arch ia32 -u ${{ secrets.GITHUB_TOKEN }}
          ${{ env.NODE_BUILD_CMD }} --arch arm64 -u ${{ secrets.GITHUB_TOKEN }}
          ${{ env.ELECTRON_BUILD_CMD }}  -u ${{ secrets.GITHUB_TOKEN }}
          ${{ env.ELECTRON_BUILD_CMD }} --arch ia32 -u ${{ secrets.GITHUB_TOKEN }}
          ${{ env.ELECTRON_BUILD_CMD }} --arch arm64 -u ${{ secrets.GITHUB_TOKEN }}

  prebuild-alpine:
    if: ${{ github.event.inputs.job == 'alpine'  || github.event.inputs.job == 'run-all' }}
    strategy:
      fail-fast: false
    name: Prebuild on alpine
    runs-on: ubuntu-latest
    container: node:18-alpine
    #needs: test
    steps:
      - uses: actions/checkout@v4
      - run: apk add build-base git python3 py3-setuptools --update-cache
      - run: npm install --ignore-scripts
      - run: ${{ env.NODE_BUILD_CMD }} -u ${{ secrets.GITHUB_TOKEN }}

  prebuild-alpine-arm:
    if: ${{ github.event.inputs.job == 'alpine-arm'  || github.event.inputs.job == 'run-all' }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm/v7
          - arm64
    name: Prebuild on alpine (${{ matrix.arch }})
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - run: |
          docker run --rm -v $(pwd):/tmp/project --entrypoint /bin/sh --platform linux/${{ matrix.arch }} node:18-alpine -c "\
          apk add build-base git python3 py3-setuptools --update-cache && \
          cd /tmp/project && \
          npm install --ignore-scripts && \
          ${{ env.NODE_BUILD_CMD }} -u ${{ secrets.GITHUB_TOKEN }}"

  prebuild-linux-arm:
    if: ${{ github.event.inputs.job == 'linux-arm'  || github.event.inputs.job == 'run-all' }}
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm/v7
          - arm64
    name: Prebuild on Linux (${{ matrix.arch }})
    runs-on: ubuntu-latest
    #needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - run: |
          docker run --rm -v $(pwd):/tmp/project --entrypoint /bin/sh --platform linux/${{ matrix.arch }} node:18-bullseye -c "\
          cd /tmp/project && \
          npm install --ignore-scripts && \
          ${{ env.NODE_BUILD_CMD }} -u ${{ secrets.GITHUB_TOKEN }}"
